// Copyright (c) 2022 Goyerv Ltd. All rights reserved.








part of 'fields.dart';

final displayLarge = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 96, fontWeight: FontWeight.w900, letterSpacing: 11.52, wordSpacing: 15.36, height: 12.48, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 96, fontWeight: FontWeight.w900, letterSpacing: 11.52, wordSpacing: 15.36, height: 13.48,));
final displayMedium = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 81, fontWeight: FontWeight.w900, letterSpacing: 9.72, wordSpacing: 12.96, height: 10.53, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 81, fontWeight: FontWeight.w900, letterSpacing: 9.72, wordSpacing: 12.96, height: 10.53,));
final displaySmall = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 51, fontWeight: FontWeight.w800, letterSpacing: 6.12, wordSpacing: 8.16, height: 6.63, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 51, fontWeight: FontWeight.w800, letterSpacing: 6.12, wordSpacing: 8.16, height: 6.63,));
final headlineLarge = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 49, fontWeight: FontWeight.w800, letterSpacing: 5.88, wordSpacing: 7.84, height: 6.37, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 49, fontWeight: FontWeight.w800, letterSpacing: 5.88, wordSpacing: 7.84, height: 6.37,));
final headlineMedium = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 35, fontWeight: FontWeight.w800, letterSpacing: 4.2, wordSpacing: 5.6, height: 4.55, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 35, fontWeight: FontWeight.w800, letterSpacing: 4.2, wordSpacing: 5.6, height: 4.55,));
final headlineSmall = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 25, fontWeight: FontWeight.w700, letterSpacing: 3.0, wordSpacing: 4.0, height: 3.25, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 25, fontWeight: FontWeight.w700, letterSpacing: 3.0, wordSpacing: 4.0, height: 3.25,));
final titleLarge = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 22, fontWeight: FontWeight.w700, letterSpacing: 2.64, wordSpacing: 3.52, height: 2.86, textStyle: TextStyle(fontSize: 22, fontWeight: FontWeight.w700, letterSpacing: 2.64,  wordSpacing: 3.52, height: 2.86,),);
final titleMedium = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 20, fontWeight: FontWeight.w600, letterSpacing: 2.40, wordSpacing: 3.2, height: 2.60, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 20, fontWeight: FontWeight.w600, letterSpacing: 2.40, wordSpacing: 3.2, height: 2.60,));
final titleSmall = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 19.0, fontWeight: FontWeight.w500, letterSpacing: 2.28, wordSpacing: 3.04, height: 2.47, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 19.0, fontWeight: FontWeight.w500, letterSpacing: 2.28, wordSpacing: 3.04, height: 2.47,));
final bodyLarge = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 18.5, fontWeight: FontWeight.w500, letterSpacing: 2.22, wordSpacing: 2.96, height: 2.41, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 18.5, fontWeight: FontWeight.w500, letterSpacing: 2.22, wordSpacing: 2.96, height: 2.41,));
final bodyMedium = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 18.25, fontWeight: FontWeight.w400, letterSpacing: 2.19, wordSpacing: 2.92, height: 2.37, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 18.25, fontWeight: FontWeight.w400, letterSpacing: 2.19, wordSpacing: 2.92, height: 2.37,));
final bodySmall = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 18.0, fontWeight: FontWeight.w400, letterSpacing: 2.16, wordSpacing: 2.88, height: 2.52, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 18.0, fontWeight: FontWeight.w400, letterSpacing: 2.16, wordSpacing: 2.88, height: 2.52,));
final labelLarge = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 17.0, fontWeight: FontWeight.w400, letterSpacing: 2.04, wordSpacing: 2.72, height: 2.19, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 17.0, fontWeight: FontWeight.w400, letterSpacing: 2.04, wordSpacing: 2.72, height: 2.19,));
final labelMedium = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 15.0, fontWeight: FontWeight.w400, letterSpacing: 1.80, wordSpacing: 2.40, height: 0.15, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 15.0, fontWeight: FontWeight.w400, letterSpacing: 1.80, wordSpacing: 2.40, height: 0.15,));
final labelSmall = GoogleFonts.epilogue(fontFeatures: <FontFeature>[const FontFeature.alternative(1)], fontSize: 13.0, fontWeight: FontWeight.w400, letterSpacing: 1.56, wordSpacing: 2.08, height: 1.69, textStyle: const TextStyle(fontFeatures: <FontFeature>[FontFeature.alternative(1)], fontSize: 13.0, fontWeight: FontWeight.w400, letterSpacing: 1.56, wordSpacing: 2.08, height: 1.69,));
